### ISSUE TITLE
Add more defaults to #__fabrik_... tables

### ISSUE THREAD

**Issue by trob** [Infokennel/fabrik4#2]
e.g.
CREATE TABLE IF NOT EXISTS `kg6fx_fabrik_elements` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`group_id` INT(4) NOT NULL,
	`plugin` VARCHAR(100) NOT NULL,
	`label` TEXT,
	`checked_out` INT(11) NOT NULL DEFAULT 0,
	`checked_out_time` datetime NULL DEFAULT NULL,
	`created` datetime NOT NULL,
	`created_by` INT(11) NOT NULL default '0',
	`created_by_alias` varchar(100) NOT NULL default ' ',
	`modified` datetime NULL DEFAULT NULL,
	`modified_by` INT(11) NOT NULL DEFAULT 0,
	`width` INT(4) NOT NULL default '20',
	`height` INT(4) NOT NULL default '0',
	`default` TEXT NOT NULLdefault '',
	`hidden` INT(1) NOT NULL default '0',
	`eval` INT(1) NOT NULL default '0',
	`ordering` INT(4) NOT NULL default '1',
	`show_in_list_summary` INT(1), 
	`filter_type` VARCHAR (20),
	`filter_exact_match` INT(1),
	`published` INT(1) NOT NULL default '0',
	`link_to_detail` INT(1) NOT NULL default '0',
	`primary_key` INT(1) NOT NULL default '0',
	`auto_increment` INT(1) NOT NULL default '0',
	`access` INT(1) NOT NULL default '0',
	`use_in_page_title` INT(1) NOT NULL default '0',
	`parent_id` MEDIUMINT(6) NOT NULL default '0',
	`params` MEDIUMTEXT NOT NULL,
	PRIMARY KEY (`id`),
	KEY `show_in_list_summary_INDEX` (`show_in_list_summary`),
	KEY `plugin_INDEX` (`plugin`(10)),
	KEY `checked_out_INDEX` (`checked_out`),
	KEY `group_id_INDEX` (`group_id`),
	KEY `parent_id_INDEX` (`parent_id`)
) DEFAULT CHARSET=utf8;

**Comment by skurvish** [comment]
You go to this before me :)
